TrueLayer/truelayer-dotnet

examples/MvcExample/MvcExample.csproj
src/TrueLayer/Payments/Model/Beneficiary.cs
src/TrueLayer/Payments/Model/PaymentMethod.cs
src/TrueLayer/Payments/Model/Provider.cs
src/TrueLayer/Payments/Model/RemitterAccount.cs
src/TrueLayer/TrueLayer.csproj
test/TrueLayer.AcceptanceTests/PaymentTests.cs
test/TrueLayer.AcceptanceTests/TrueLayer.AcceptanceTests.csproj
test/TrueLayer.AcceptanceTests/appsettings.json

This PR is implementi the `PRESELECTED` provider filter for the `Create-Payment` endpoint as described in this [documentation](https://docs.truelayer.com/reference/create-payment).
Closes #131

[ISSUE-131] Add `preselected` Provider filter for `Create-Payment` endpoint

---

README.md
examples/MvcExample/Controllers/PayoutController.cs
src/TrueLayer/Payouts/IPayoutsApi.cs
src/TrueLayer/Payouts/Model/Beneficiary.cs
src/TrueLayer/Payouts/Model/GetPayoutsResponse.cs
src/TrueLayer/Payouts/PayoutsApi.cs
test/TrueLayer.Tests/Payouts/PayoutsApiTests.cs

With this PR, users will be able to send out payouts using the `payment_source` type. This will facilitate payouts operations when a user has alsready made a payment towards your `merchant_account`.
More info can be found on our official [documentation](https://docs.truelayer.com/docs/when-to-use-payouts#payout-to-an-user).
Closes #134

[SPAIN-367] Enable payment_source for payouts

---

examples/MvcExample/Controllers/PayoutController.cs
src/TrueLayer/Payouts/IPayoutsApi.cs
src/TrueLayer/Payouts/Model/GetPayoutsResponse.cs
src/TrueLayer/Payouts/PayoutsApi.cs

There is no longer a `successful` status for payouts, this has been replaced with `executed` (which is already implemented in this SDK from a previous PR).

[ISSUE-141] Remove payouts successful status (no longer used)

---

src/TrueLayer/Payouts/Model/Beneficiary.cs
src/TrueLayer/Payouts/Model/CreatePayoutRequest.cs
test/TrueLayer.Tests/Payouts/PayoutsApiTests.cs

Payouts has exposed a new beneficiary type, `business_account`. This allows payouts to a client's preconfigured business account IBAN. This PR adds support for this beneficiary type.

[ISSUE-140] Add business account payout beneficiary

---

examples/MvcExample/Controllers/HomeController.cs
examples/MvcExample/Models/DonateModel.cs
examples/MvcExample/Views/Home/Failed.cshtml
examples/MvcExample/Views/Home/Index.cshtml
examples/MvcExample/Views/Home/Pending.cshtml
examples/MvcExample/Views/Home/Success.cshtml
src/TrueLayer/Extensions/UriExtensions.cs
src/TrueLayer/Payments/Model/Provider.cs
src/TrueLayer/Payouts/Model/Beneficiary.cs
test/TrueLayer.AcceptanceTests/PaymentTests.cs

Closes #133 
Extra:
- Added an option to specify whether to use a preselected filter or a user-selected one in the demo page
- Fixed typo in `Payout.Beneficiary.ExternalAccount`
- Provided `ApiRepsonse<T>.ToJson<T>()` extension method to get the API response as `json` using the internal `JsonSerialiser`

[ISSUE-133] Return provider data from user selected filter

---

examples/MvcExample/Controllers/HomeController.cs
src/TrueLayer/Payments/IPaymentsApi.cs
src/TrueLayer/Payments/Model/CreatePaymentResponse.cs
src/TrueLayer/Payments/Model/GetPaymentResponse.cs
src/TrueLayer/Payments/PaymentsApi.cs
test/TrueLayer.AcceptanceTests/MerchantAccountsTests.cs
test/TrueLayer.AcceptanceTests/PaymentTests.cs
test/TrueLayer.Benchmarks/SerializationBenchmarks.cs

The create payment response now includes a `status` field to disambiguate the cases where a payment requires authorisation, was created at an already authorised state, or was created but then failed.

[PAYG-1150][PAYG-1168] Add status to create payment response

---

.github/workflows/build.yml
.github/workflows/publish.yml
examples/MvcExample/MvcExample.csproj
global.json
src/TrueLayer/ApiClient.cs
src/TrueLayer/ApiResponseOfT.cs
src/TrueLayer/Serialization/SerializerOptions.cs
src/TrueLayer/SigningKey.cs
src/TrueLayer/TrueLayer.csproj
test/TrueLayer.AcceptanceTests/TrueLayer.AcceptanceTests.csproj
test/TrueLayer.Benchmarks/TrueLayer.Benchmarks.csproj
test/TrueLayer.Tests/TrueLayer.Tests.csproj

`.NET 5` is not supported anymore since [May 10, 2022](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core). That's why we need to migrate to `.NET 6`.
We're also updating all the [predefined preprocessor symbols](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives#conditional-compilation).

[EWT-42] Upgrade to `.NET 6`

---

src/TrueLayer/Payments/Model/Beneficiary.cs
src/TrueLayer/Payments/Model/PaymentMethod.cs
src/TrueLayer/Payments/Model/Provider.cs
src/TrueLayer/Payments/Model/ProviderFilter.cs
src/TrueLayer/TrueLayerOptions.cs
test/TrueLayer.AcceptanceTests/MerchantAccountsTests.cs

The [`Beneficiary.MerchantAccount`](https://github.com/TrueLayer/truelayer-dotnet/blob/main/src/TrueLayer/Payments/Model/Beneficiary.cs#L15) request record doesn't currently allow to specify the `Reference` for the payment request as specified in the [documentation](https://docs.truelayer.com/reference/create-payment).
This PR adds the field to the request object.
Extra:
- Fixed xml doc for some of the properties in record objects

[NETSDK-1] Add reference field to Beneficiary.MerchantAccount

---

src/TrueLayer/Payments/Model/PaymentUser.cs
test/TrueLayer.AcceptanceTests/PaymentTests.cs

**Description:** 
Remove user info from the `GET /payment` response.
**Changelog:**
https://docs.truelayer.com/changelog/removal-of-user-info-in-payment-and-mandate-response
**Updated documentation**
https://docs.truelayer.com/reference/get-payment-1
https://docs.truelayer.com/reference/get-mandate

feat(PAYG-1374): Remove user info from get payment response

---

CHANGELOG.md
src/TrueLayer/Payments/Model/ProviderFilter.cs

This is a **breaking change** since the field is changed from `string` to `string[]`.

fix: [EWT-80] Change `CustomerSegments` to array accordingly with PaymentV3 docs

---

examples/MvcExample/Controllers/HomeController.cs
src/TrueLayer/Payments/Model/Address.cs
src/TrueLayer/Payments/Model/PaymentUserRequest.cs
src/TrueLayer/Serialization/DateTimeDateOnlyJsonConverter.cs
src/TrueLayer/TrueLayer.csproj
test/TrueLayer.AcceptanceTests/MerchantAccountsTests.cs
test/TrueLayer.AcceptanceTests/PaymentTests.cs
test/TrueLayer.Tests/Payments/AddressTests.cs
test/TrueLayer.Tests/Payments/PaymentUserRequestTests.cs

This PRs adds the following field to the `PaymentUserRequest` object to align it with the official [documentation](https://docs.truelayer.com/reference/create-payment):
- `DateOfBirth` (with custom JSON formatter to serialise it to `"yyyy-MM-dd"`)
- `Address`
Amended test and sample app accordingly.

feat(EWT-111): Add more user info to the payment user request

---

.github/workflows/build.yml
.github/workflows/publish.yml
CHANGELOG.md
TrueLayer.sln

New tag 1.2.0 got pushed to replace version 1.1.0.
Updated the changelog accordingly.
Extra:
- updated workflows runner to `ubunto-22.04` (see [this issue](https://github.com/actions/runner-images/issues/6002) for more details)

[EWT-111]: updated CHANGELOG

---

src/TrueLayer/Payments/Model/Provider.cs
src/TrueLayer/Payments/Model/SchemeSelection.cs
test/TrueLayer.AcceptanceTests/PaymentTests.cs

This PR implements the new scheme selection options from the [CreatePAyment](https://docs.truelayer.com/reference/create-payment) request that are replacing the old structure based on `scheme_id`.

feat(pfi-305): implement new scheme selection option when creating a payment

---

src/TrueLayer/PaymentsProviders/PaymentsProvidersApi.cs
src/TrueLayer/TrueLayerClient.cs

The endpoint now requires `Authorization` header.
The `client_id` query parameter is not needed anymore as it is fetched from the token's claims.

feat(PAYINS-504): Set Authorization header to `GET v3/payments-providers/{id}`

---

examples/MvcExample/Controllers/HomeController.cs
src/TrueLayer/Payments/Model/Provider.cs

#203 introduced made the `Preselected` provider selection method obsolete by mistake. This PR is reverting the change.

fix(acl-20): remove unnecessary obsolete tags

---

src/TrueLayer/PaymentsProviders/Model/SearchPaymentsProvidersRequest.cs
test/TrueLayer.AcceptanceTests/PaymentsProvidersTests.cs

#199 introduced the support to the search providers endpoint but unfortunately the `SeachPaymentsProvidersRequest` had a wrong `ReleaseChannels` parameter. This PR is fixing it (see [doc](https://docs.truelayer.com/reference/search-payment-providers)).

fix(acl-176): fix releaseChannel parameter in SearchPaymentsProvidersRequest

---

examples/MvcExample/Controllers/HomeController.cs
src/TrueLayer/Payments/IPaymentsApi.cs
src/TrueLayer/Payments/Model/AuthorizationFlow/AuthorizationFlow.cs
src/TrueLayer/Payments/Model/AuthorizationFlow/AuthorizationFlowAction.cs
src/TrueLayer/Payments/Model/CreatePaymentResponse.cs
src/TrueLayer/Payments/Model/GetPaymentResponse.cs
src/TrueLayer/Payments/Model/PaymentMethod.cs
src/TrueLayer/Payments/Model/Retry.cs
src/TrueLayer/Payments/PaymentsApi.cs
src/TrueLayer/Serialization/OneOfJsonConverter.cs
test/TrueLayer.AcceptanceTests/MandatesTests.cs
test/TrueLayer.AcceptanceTests/PaymentTests.cs
test/TrueLayer.AcceptanceTests/TestUtils.cs
test/TrueLayer.Tests/Serialization/OneOfJsonConverterTests.cs

This PR implements the support to the `Retry` option for the `CreatePaymentRequest` and the new `attempt_failed` payment status. 
More details can be found [here](https://docs.truelayer.com/docs/web-sdk#payment-retries-for-web-sdk).

feat(ACL-132, ACL-134) add support to retry option for the `CreatePAymentRequest` and `attempt_failed`  response type

---

src/TrueLayer/Payments/IPaymentsApi.cs
src/TrueLayer/Payments/PaymentsApi.cs
test/TrueLayer.AcceptanceTests/PaymentTests.cs

Add `POST /payments/{id}/actions/cancel` endpoint support with acceptance tests

[ACL-96] Add cancel payment endpoint

---

test/TrueLayer.AcceptanceTests/AuthTests.cs
test/TrueLayer.AcceptanceTests/MandatesTests.cs
test/TrueLayer.AcceptanceTests/MerchantAccountsTests.cs
test/TrueLayer.AcceptanceTests/PaymentTests.AuthFlow.cs
test/TrueLayer.AcceptanceTests/PaymentTests.cs
test/TrueLayer.AcceptanceTests/PaymentsProvidersTests.cs
test/TrueLayer.AcceptanceTests/PayoutTests.cs
test/TrueLayer.AcceptanceTests/TestUtils.cs
test/TrueLayer.AcceptanceTests/TrueLayer.AcceptanceTests.csproj
test/TrueLayer.Tests/ApiClientTests.cs
test/TrueLayer.Tests/ApiResponseTests.cs
test/TrueLayer.Tests/CurrencyExtensionsTests.cs
test/TrueLayer.Tests/Extensions/UriExtensionsTests.cs
test/TrueLayer.Tests/HppLinkBuilderTests.cs
test/TrueLayer.Tests/Payments/PaymentUserRequestTests.cs
test/TrueLayer.Tests/Payouts/PayoutsApiTests.cs
test/TrueLayer.Tests/RequestSignatureTests.cs
test/TrueLayer.Tests/Serialization/OneOfJsonConverterFactoryTests.cs
test/TrueLayer.Tests/Serialization/OneOfJsonConverterTests.cs
test/TrueLayer.Tests/Serialization/OneOfTypeDescriptorTests.cs
test/TrueLayer.Tests/Serialization/PolymorphicJsonConverterTests.cs
test/TrueLayer.Tests/Serialization/SerializationTests.cs
test/TrueLayer.Tests/TrueLayer.Tests.csproj
test/TrueLayer.Tests/TrueLayerApiExceptionTests.cs
test/TrueLayer.Tests/TrueLayerClientTests.cs
test/TrueLayer.Tests/TrueLayerServiceCollectionExtensionsTests.cs

Remove Shouldly and switch to FluentAssertions
Update dependecies and fix xunit issues

Test improvements

---

Directory.Build.props
src/TrueLayer/TrueLayer.csproj
test/TrueLayer.Tests/TrueLayer.Tests.csproj
test/TrueLayer.Tests/TrueLayerServiceCollectionExtensionsTests.cs

>  Warning
> 
> Setting the LangVersion element to latest is discouraged. The latest setting means the installed compiler uses its latest version. That can change from machine to machine, making builds unreliable. In addition, it enables language features that may require runtime or library features not included in the current SDK.

Set LangVersion to 10.0 as latest is discouraged

---

src/TrueLayer/Payments/Model/GetPaymentResponse.cs
test/TrueLayer.AcceptanceTests/Helpers/Waiter.cs
test/TrueLayer.AcceptanceTests/MockBank/MockBankAction.cs
test/TrueLayer.AcceptanceTests/MockBank/MockBankClient.cs
test/TrueLayer.AcceptanceTests/PayApiClient.cs
test/TrueLayer.AcceptanceTests/PaymentTests.cs

Added CreditableAt in `Authorized`, `Executed` and `Settled` case of `GetPayment`.
Added test for GetPayment when status is `Settled`

[ACL-242] Add CreditableAt in GetPaymentResult
